config/routes.rb
Rails.application.routes.draw do
  resources :kickers
  resources :defenses
  resources :wide_receivers
  resources :tight_ends
  resources :running_backs
  root 'homes#index'
  devise_for :users

  resources :leagues do
    resources :teams
  end
    
  resources :teams do  
    resources :qbs
  end

end

app/models/tight_end.rb
class TightEnd < ActiveRecord::Base
end

app/controllers/tight_ends_controller.rb
class TightEndsController < ApplicationController
  before_action :set_tight_end, only: [:show, :edit, :update, :destroy]

  # GET /tight_ends
  # GET /tight_ends.json
  def index
    @tight_ends = TightEnd.all
  end

  # GET /tight_ends/1
  # GET /tight_ends/1.json
  def show
  end

  # GET /tight_ends/new
  def new
    @tight_end = TightEnd.new
  end

  # GET /tight_ends/1/edit
  def edit
  end

  # POST /tight_ends
  # POST /tight_ends.json
  def create
    @tight_end = TightEnd.new(tight_end_params)

    respond_to do |format|
      if @tight_end.save
        format.html { redirect_to @tight_end, notice: 'Tight end was successfully created.' }
        format.json { render :show, status: :created, location: @tight_end }
      else
        format.html { render :new }
        format.json { render json: @tight_end.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tight_ends/1
  # PATCH/PUT /tight_ends/1.json
  def update
    respond_to do |format|
      if @tight_end.update(tight_end_params)
        format.html { redirect_to @tight_end, notice: 'Tight end was successfully updated.' }
        format.json { render :show, status: :ok, location: @tight_end }
      else
        format.html { render :edit }
        format.json { render json: @tight_end.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tight_ends/1
  # DELETE /tight_ends/1.json
  def destroy
    @tight_end.destroy
    respond_to do |format|
      format.html { redirect_to tight_ends_url, notice: 'Tight end was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tight_end
      @tight_end = TightEnd.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tight_end_params
      params.require(:tight_end).permit(:player_name, :week, :touchdowns, :yards, :receptions)
    end
end

app/helpers/tight_ends_helper.rb
module TightEndsHelper
end

app/views/tight_ends/_form.html.erb
<%= form_for(@tight_end) do |f| %>
  <% if @tight_end.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@tight_end.errors.count, "error") %> prohibited this tight_end from being saved:</h2>

      <ul>
      <% @tight_end.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :player_name %><br>
    <%= f.text_field :player_name %>
  </div>
  <div class="field">
    <%= f.label :week %><br>
    <%= f.number_field :week %>
  </div>
  <div class="field">
    <%= f.label :touchdowns %><br>
    <%= f.number_field :touchdowns %>
  </div>
  <div class="field">
    <%= f.label :yards %><br>
    <%= f.number_field :yards %>
  </div>
  <div class="field">
    <%= f.label :receptions %><br>
    <%= f.number_field :receptions %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tight_ends/edit.html.erb
<h1>Editing Tight End</h1>

<%= render 'form' %>

<%= link_to 'Show', @tight_end %> |
<%= link_to 'Back', tight_ends_path %>

app/views/tight_ends/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Tight Ends</h1>

<table>
  <thead>
    <tr>
      <th>Player name</th>
      <th>Week</th>
      <th>Touchdowns</th>
      <th>Yards</th>
      <th>Receptions</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tight_ends.each do |tight_end| %>
      <tr>
        <td><%= tight_end.player_name %></td>
        <td><%= tight_end.week %></td>
        <td><%= tight_end.touchdowns %></td>
        <td><%= tight_end.yards %></td>
        <td><%= tight_end.receptions %></td>
        <td><%= link_to 'Show', tight_end %></td>
        <td><%= link_to 'Edit', edit_tight_end_path(tight_end) %></td>
        <td><%= link_to 'Destroy', tight_end, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Tight end', new_tight_end_path %>

app/views/tight_ends/new.html.erb
<h1>New Tight End</h1>

<%= render 'form' %>

<%= link_to 'Back', tight_ends_path %>

app/views/tight_ends/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Player name:</strong>
  <%= @tight_end.player_name %>
</p>

<p>
  <strong>Week:</strong>
  <%= @tight_end.week %>
</p>

<p>
  <strong>Touchdowns:</strong>
  <%= @tight_end.touchdowns %>
</p>

<p>
  <strong>Yards:</strong>
  <%= @tight_end.yards %>
</p>

<p>
  <strong>Receptions:</strong>
  <%= @tight_end.receptions %>
</p>

<%= link_to 'Edit', edit_tight_end_path(@tight_end) %> |
<%= link_to 'Back', tight_ends_path %>