config/routes.rb
Rails.application.routes.draw do
  resources :kickers
  resources :defenses
  resources :wide_receivers
  resources :tight_ends
  resources :running_backs
  root 'homes#index'
  devise_for :users

  resources :leagues do
    resources :teams
  end
    
  resources :teams do  
    resources :qbs
  end

end

app/models/qb.rb
class Qb < ActiveRecord::Base
end

app/controllers/q_bs_controller.rb
class QBsController < ApplicationController
  before_action :set_qb, only: [:show, :edit, :update, :destroy]

  # GET /qbs
  # GET /qbs.json
  def index
    @qbs = Qb.all
  end

  # GET /qbs/1
  # GET /qbs/1.json
  def show
  end

  # GET /qbs/new
  def new
    @qb = Qb.new
  end

  # GET /qbs/1/edit
  def edit
  end

  # POST /qbs
  # POST /qbs.json
  def create
    @qb = Qb.new(qb_params)

    respond_to do |format|
      if @qb.save
        format.html { redirect_to @qb, notice: 'Qb was successfully created.' }
        format.json { render :show, status: :created, location: @qb }
      else
        format.html { render :new }
        format.json { render json: @qb.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /qbs/1
  # PATCH/PUT /qbs/1.json
  def update
    respond_to do |format|
      if @qb.update(qb_params)
        format.html { redirect_to @qb, notice: 'Qb was successfully updated.' }
        format.json { render :show, status: :ok, location: @qb }
      else
        format.html { render :edit }
        format.json { render json: @qb.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /qbs/1
  # DELETE /qbs/1.json
  def destroy
    @qb.destroy
    respond_to do |format|
      format.html { redirect_to qbs_url, notice: 'Qb was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_qb
      @qb = Qb.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def qb_params
      params.require(:qb).permit(:player_name, :week, :pass_attempts, :pass_completes, :touchdowns, :interceptions, :fumbles)
    end
end

app/helpers/q_bs_helper.rb
module QBsHelper
end

app/views/q_bs/_form.html.erb
<%= form_for(@qb) do |f| %>
  <% if @qb.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@qb.errors.count, "error") %> prohibited this qb from being saved:</h2>

      <ul>
      <% @qb.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :player_name %><br>
    <%= f.text_field :player_name %>
  </div>
  <div class="field">
    <%= f.label :week %><br>
    <%= f.number_field :week %>
  </div>
  <div class="field">
    <%= f.label :pass_attempts %><br>
    <%= f.number_field :pass_attempts %>
  </div>
  <div class="field">
    <%= f.label :pass_completes %><br>
    <%= f.number_field :pass_completes %>
  </div>
  <div class="field">
    <%= f.label :touchdowns %><br>
    <%= f.number_field :touchdowns %>
  </div>
  <div class="field">
    <%= f.label :interceptions %><br>
    <%= f.number_field :interceptions %>
  </div>
  <div class="field">
    <%= f.label :fumbles %><br>
    <%= f.number_field :fumbles %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/q_bs/edit.html.erb
<h1>Editing Qb</h1>

<%= render 'form' %>

<%= link_to 'Show', @qb %> |
<%= link_to 'Back', qbs_path %>

app/views/q_bs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Qbs</h1>

<table>
  <thead>
    <tr>
      <th>Player name</th>
      <th>Week</th>
      <th>Pass attempts</th>
      <th>Pass completes</th>
      <th>Touchdowns</th>
      <th>Interceptions</th>
      <th>Fumbles</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @qbs.each do |qb| %>
      <tr>
        <td><%= qb.player_name %></td>
        <td><%= qb.week %></td>
        <td><%= qb.pass_attempts %></td>
        <td><%= qb.pass_completes %></td>
        <td><%= qb.touchdowns %></td>
        <td><%= qb.interceptions %></td>
        <td><%= qb.fumbles %></td>
        <td><%= link_to 'Show', qb %></td>
        <td><%= link_to 'Edit', edit_qb_path(qb) %></td>
        <td><%= link_to 'Destroy', qb, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Qb', new_qb_path %>

app/views/q_bs/new.html.erb
<h1>New Qb</h1>

<%= render 'form' %>

<%= link_to 'Back', qbs_path %>

app/views/q_bs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Player name:</strong>
  <%= @qb.player_name %>
</p>

<p>
  <strong>Week:</strong>
  <%= @qb.week %>
</p>

<p>
  <strong>Pass attempts:</strong>
  <%= @qb.pass_attempts %>
</p>

<p>
  <strong>Pass completes:</strong>
  <%= @qb.pass_completes %>
</p>

<p>
  <strong>Touchdowns:</strong>
  <%= @qb.touchdowns %>
</p>

<p>
  <strong>Interceptions:</strong>
  <%= @qb.interceptions %>
</p>

<p>
  <strong>Fumbles:</strong>
  <%= @qb.fumbles %>
</p>

<%= link_to 'Edit', edit_qb_path(@qb) %> |
<%= link_to 'Back', qbs_path %>