config/routes.rb
Rails.application.routes.draw do
  resources :kickers
  resources :defenses
  resources :wide_receivers
  resources :tight_ends
  resources :running_backs
  root 'homes#index'
  devise_for :users

  resources :leagues do
    resources :teams
  end
    
  resources :teams do  
    resources :qbs
  end

end

app/models/running_back.rb
class RunningBack < ActiveRecord::Base
end

app/controllers/running_backs_controller.rb
class RunningBacksController < ApplicationController
  before_action :set_running_back, only: [:show, :edit, :update, :destroy]

  # GET /running_backs
  # GET /running_backs.json
  def index
    @running_backs = RunningBack.all
  end

  # GET /running_backs/1
  # GET /running_backs/1.json
  def show
  end

  # GET /running_backs/new
  def new
    @running_back = RunningBack.new
  end

  # GET /running_backs/1/edit
  def edit
  end

  # POST /running_backs
  # POST /running_backs.json
  def create
    @running_back = RunningBack.new(running_back_params)

    respond_to do |format|
      if @running_back.save
        format.html { redirect_to @running_back, notice: 'Running back was successfully created.' }
        format.json { render :show, status: :created, location: @running_back }
      else
        format.html { render :new }
        format.json { render json: @running_back.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /running_backs/1
  # PATCH/PUT /running_backs/1.json
  def update
    respond_to do |format|
      if @running_back.update(running_back_params)
        format.html { redirect_to @running_back, notice: 'Running back was successfully updated.' }
        format.json { render :show, status: :ok, location: @running_back }
      else
        format.html { render :edit }
        format.json { render json: @running_back.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /running_backs/1
  # DELETE /running_backs/1.json
  def destroy
    @running_back.destroy
    respond_to do |format|
      format.html { redirect_to running_backs_url, notice: 'Running back was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_running_back
      @running_back = RunningBack.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def running_back_params
      params.require(:running_back).permit(:player_name, :touchdowns, :yards, :receptions, :week)
    end
end

app/helpers/running_backs_helper.rb
module RunningBacksHelper
end

app/views/running_backs/_form.html.erb
<%= form_for(@running_back) do |f| %>
  <% if @running_back.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@running_back.errors.count, "error") %> prohibited this running_back from being saved:</h2>

      <ul>
      <% @running_back.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :player_name %><br>
    <%= f.text_field :player_name %>
  </div>
  <div class="field">
    <%= f.label :touchdowns %><br>
    <%= f.number_field :touchdowns %>
  </div>
  <div class="field">
    <%= f.label :yards %><br>
    <%= f.number_field :yards %>
  </div>
  <div class="field">
    <%= f.label :receptions %><br>
    <%= f.number_field :receptions %>
  </div>
  <div class="field">
    <%= f.label :week %><br>
    <%= f.number_field :week %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/running_backs/edit.html.erb
<h1>Editing Running Back</h1>

<%= render 'form' %>

<%= link_to 'Show', @running_back %> |
<%= link_to 'Back', running_backs_path %>

app/views/running_backs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Running Backs</h1>

<table>
  <thead>
    <tr>
      <th>Player name</th>
      <th>Touchdowns</th>
      <th>Yards</th>
      <th>Receptions</th>
      <th>Week</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @running_backs.each do |running_back| %>
      <tr>
        <td><%= running_back.player_name %></td>
        <td><%= running_back.touchdowns %></td>
        <td><%= running_back.yards %></td>
        <td><%= running_back.receptions %></td>
        <td><%= running_back.week %></td>
        <td><%= link_to 'Show', running_back %></td>
        <td><%= link_to 'Edit', edit_running_back_path(running_back) %></td>
        <td><%= link_to 'Destroy', running_back, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Running back', new_running_back_path %>

app/views/running_backs/new.html.erb
<h1>New Running Back</h1>

<%= render 'form' %>

<%= link_to 'Back', running_backs_path %>

app/views/running_backs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Player name:</strong>
  <%= @running_back.player_name %>
</p>

<p>
  <strong>Touchdowns:</strong>
  <%= @running_back.touchdowns %>
</p>

<p>
  <strong>Yards:</strong>
  <%= @running_back.yards %>
</p>

<p>
  <strong>Receptions:</strong>
  <%= @running_back.receptions %>
</p>

<p>
  <strong>Week:</strong>
  <%= @running_back.week %>
</p>

<%= link_to 'Edit', edit_running_back_path(@running_back) %> |
<%= link_to 'Back', running_backs_path %>