config/routes.rb
Rails.application.routes.draw do
  resources :kickers
  resources :defenses
  resources :wide_receivers
  resources :tight_ends
  resources :running_backs
  root 'homes#index'
  devise_for :users

  resources :leagues do
    resources :teams
  end
    
  resources :teams do  
    resources :qbs
  end

end

app/models/wide_receiver.rb
class WideReceiver < ActiveRecord::Base
end

app/controllers/wide_receivers_controller.rb
class WideReceiversController < ApplicationController
  before_action :set_wide_receiver, only: [:show, :edit, :update, :destroy]

  # GET /wide_receivers
  # GET /wide_receivers.json
  def index
    @wide_receivers = WideReceiver.all
  end

  # GET /wide_receivers/1
  # GET /wide_receivers/1.json
  def show
  end

  # GET /wide_receivers/new
  def new
    @wide_receiver = WideReceiver.new
  end

  # GET /wide_receivers/1/edit
  def edit
  end

  # POST /wide_receivers
  # POST /wide_receivers.json
  def create
    @wide_receiver = WideReceiver.new(wide_receiver_params)

    respond_to do |format|
      if @wide_receiver.save
        format.html { redirect_to @wide_receiver, notice: 'Wide receiver was successfully created.' }
        format.json { render :show, status: :created, location: @wide_receiver }
      else
        format.html { render :new }
        format.json { render json: @wide_receiver.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /wide_receivers/1
  # PATCH/PUT /wide_receivers/1.json
  def update
    respond_to do |format|
      if @wide_receiver.update(wide_receiver_params)
        format.html { redirect_to @wide_receiver, notice: 'Wide receiver was successfully updated.' }
        format.json { render :show, status: :ok, location: @wide_receiver }
      else
        format.html { render :edit }
        format.json { render json: @wide_receiver.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /wide_receivers/1
  # DELETE /wide_receivers/1.json
  def destroy
    @wide_receiver.destroy
    respond_to do |format|
      format.html { redirect_to wide_receivers_url, notice: 'Wide receiver was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_wide_receiver
      @wide_receiver = WideReceiver.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def wide_receiver_params
      params.require(:wide_receiver).permit(:player_name, :touchdowns, :yards, :receptions, :week)
    end
end

app/helpers/wide_receivers_helper.rb
module WideReceiversHelper
end

app/views/wide_receivers/_form.html.erb
<%= form_for(@wide_receiver) do |f| %>
  <% if @wide_receiver.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@wide_receiver.errors.count, "error") %> prohibited this wide_receiver from being saved:</h2>

      <ul>
      <% @wide_receiver.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :player_name %><br>
    <%= f.text_field :player_name %>
  </div>
  <div class="field">
    <%= f.label :touchdowns %><br>
    <%= f.number_field :touchdowns %>
  </div>
  <div class="field">
    <%= f.label :yards %><br>
    <%= f.number_field :yards %>
  </div>
  <div class="field">
    <%= f.label :receptions %><br>
    <%= f.number_field :receptions %>
  </div>
  <div class="field">
    <%= f.label :week %><br>
    <%= f.number_field :week %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/wide_receivers/edit.html.erb
<h1>Editing Wide Receiver</h1>

<%= render 'form' %>

<%= link_to 'Show', @wide_receiver %> |
<%= link_to 'Back', wide_receivers_path %>

app/views/wide_receivers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Wide Receivers</h1>

<table>
  <thead>
    <tr>
      <th>Player name</th>
      <th>Touchdowns</th>
      <th>Yards</th>
      <th>Receptions</th>
      <th>Week</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @wide_receivers.each do |wide_receiver| %>
      <tr>
        <td><%= wide_receiver.player_name %></td>
        <td><%= wide_receiver.touchdowns %></td>
        <td><%= wide_receiver.yards %></td>
        <td><%= wide_receiver.receptions %></td>
        <td><%= wide_receiver.week %></td>
        <td><%= link_to 'Show', wide_receiver %></td>
        <td><%= link_to 'Edit', edit_wide_receiver_path(wide_receiver) %></td>
        <td><%= link_to 'Destroy', wide_receiver, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Wide receiver', new_wide_receiver_path %>

app/views/wide_receivers/new.html.erb
<h1>New Wide Receiver</h1>

<%= render 'form' %>

<%= link_to 'Back', wide_receivers_path %>

app/views/wide_receivers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Player name:</strong>
  <%= @wide_receiver.player_name %>
</p>

<p>
  <strong>Touchdowns:</strong>
  <%= @wide_receiver.touchdowns %>
</p>

<p>
  <strong>Yards:</strong>
  <%= @wide_receiver.yards %>
</p>

<p>
  <strong>Receptions:</strong>
  <%= @wide_receiver.receptions %>
</p>

<p>
  <strong>Week:</strong>
  <%= @wide_receiver.week %>
</p>

<%= link_to 'Edit', edit_wide_receiver_path(@wide_receiver) %> |
<%= link_to 'Back', wide_receivers_path %>